### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'hinted_json_file'

### ISSUE THREAD

**Issue by walkerbatista** [Nuitka/NUITKA-Utilities#38]
Hi, I'm trying to run _'python nuitka-hints.py myscript.py'_ and I get this error:

NUITKA v0.6.7 on Python 3.7.7 (win32) is compiling 'myscript.py' with these options:
 --standalone
 --recurse-none
aqui
Nuitka:INFO:User plugin 'py' is being loaded.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\teste_nuitka\lib\site-packages\nuitka\__main__.py", line 182, in <module>
    main()
  File "C:\ProgramData\Anaconda3\envs\teste_nuitka\lib\site-packages\nuitka\__main__.py", line 173, in main
    from nuitka import MainControl  # isort:skip
  File "C:\ProgramData\Anaconda3\envs\teste_nuitka\lib\site-packages\nuitka\MainControl.py", line 32, in <module>
    from nuitka.finalizations.FinalizeMarkups import getImportedNames
  File "C:\ProgramData\Anaconda3\envs\teste_nuitka\lib\site-packages\nuitka\finalizations\FinalizeMarkups.py", line 38, in <module>
    from nuitka.importing.Importing import isWhiteListedImport
  File "C:\ProgramData\Anaconda3\envs\teste_nuitka\lib\site-packages\nuitka\importing\Importing.py", line 50, in <module>
    from nuitka.plugins.Plugins import Plugins
  File "C:\ProgramData\Anaconda3\envs\teste_nuitka\lib\site-packages\nuitka\plugins\Plugins.py", line 576, in <module>
    initPlugins()
  File "C:\ProgramData\Anaconda3\envs\teste_nuitka\lib\site-packages\nuitka\plugins\Plugins.py", line 545, in initPlugins
    importUserPlugins()
  File "C:\ProgramData\Anaconda3\envs\teste_nuitka\lib\site-packages\nuitka\plugins\Plugins.py", line 520, in importUserPlugins
    active_plugin_list.append(obj())
TypeError: __init__() missing 1 required positional argument: 'hinted_json_file'

**Comment by deajan** [comment]
Current hinted compilation is set to work with Nuitka 0.6.8rc5+ since the plugin infrastructure has changed. Please update to latest Nuitka develop version for now.
If you cannot update, I can set a tag on an earlier hinted compilation point for Nuitka 0.6.7.

**Comment by walkerbatista** [comment]
Worked, thanks.
